"""Schemas for the Advisory and Evidence/Reporting agents."""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class Language(str, Enum):
    ENGLISH = "en"
    HINDI = "hi"
    TAMIL = "ta"


LANGUAGE_NAMES = {
    Language.ENGLISH: "English",
    Language.HINDI: "Hindi (हिन्दी)",
    Language.TAMIL: "Tamil (தமிழ்)",
}


class AdvisoryCitation(BaseModel):
    advisory_id: str
    title: str
    source: str


class WarningUrgency(str, Enum):
    INFO = "info"
    CAUTION = "caution"
    WARNING = "warning"
    CRITICAL = "critical"


class AdvisoryWarning(BaseModel):
    """A regulation-backed warning delivered to the person being targeted."""

    language: Language
    urgency: WarningUrgency
    headline: str = Field(description="One line. Must survive being read in 2 seconds.")
    body: str = Field(description="Plain language, addressed to the person.")
    immediate_actions: list[str] = Field(
        default_factory=list, description="What to do right now, in order."
    )
    citations: list[AdvisoryCitation] = Field(default_factory=list)
    disclaimer: str
    degraded: bool = Field(
        default=False, description="True when built from templates, LLM unavailable."
    )


class ComplaintEvidence(BaseModel):
    """One quoted red-flag line, with provenance."""

    timestamp: str | None
    turn_index: int | None
    speaker: str
    quote: str
    significance: str


class ComplaintPacket(BaseModel):
    """NCRB-style structured complaint draft.

    Illustrative format for a prototype — it is NOT an official NCRB submission and
    is not filed anywhere. It is a pre-filled draft to save a victim from writing a
    complaint from memory, hours after the fact, while distressed.
    """

    complaint_id: str
    generated_at: str
    session_id: str

    incident_type: str
    incident_summary: str
    scam_probability: int
    estimated_loss: str | None = None

    suspect_phone_numbers: list[str] = Field(default_factory=list)
    suspect_upi_ids: list[str] = Field(default_factory=list)
    suspect_bank_accounts: list[str] = Field(default_factory=list)
    suspect_claimed_identity: list[str] = Field(default_factory=list)
    suspect_claimed_agency: list[str] = Field(default_factory=list)
    fake_case_references: list[str] = Field(default_factory=list)
    suspect_urls: list[str] = Field(default_factory=list)

    evidence: list[ComplaintEvidence] = Field(default_factory=list)

    linked_cluster_id: str | None = None
    linked_session_count: int = 0
    linked_sessions: list[str] = Field(default_factory=list)
    network_note: str | None = None

    applicable_provisions: list[str] = Field(default_factory=list)
    recommended_channels: list[str] = Field(default_factory=list)

    disclaimer: str
    degraded: bool = False

    def to_text(self) -> str:
        """Human-readable complaint, for printing or pasting into a portal."""
        lines: list[str] = []
        add = lines.append

        add("=" * 72)
        add("CYBER FRAUD COMPLAINT — DRAFT")
        add("Generated by AntiScam AI (prototype)")
        add("=" * 72)
        add("")
        add(f"Complaint reference : {self.complaint_id}")
        add(f"Generated at        : {self.generated_at}")
        add(f"Session reference   : {self.session_id}")
        add("")
        add("-" * 72)
        add("1. NATURE OF INCIDENT")
        add("-" * 72)
        add(f"Type            : {self.incident_type}")
        add(f"Risk assessment : {self.scam_probability}/100")
        if self.estimated_loss:
            add(f"Amount involved : {self.estimated_loss}")
        add("")
        add("Summary:")
        for line in _wrap(self.incident_summary, 68):
            add(f"  {line}")
        add("")

        add("-" * 72)
        add("2. SUSPECT IDENTIFIERS")
        add("-" * 72)
        for label, values in (
            ("Phone numbers", self.suspect_phone_numbers),
            ("UPI IDs", self.suspect_upi_ids),
            ("Bank accounts", self.suspect_bank_accounts),
            ("Claimed identity", self.suspect_claimed_identity),
            ("Claimed agency", self.suspect_claimed_agency),
            ("Case refs cited", self.fake_case_references),
            ("URLs", self.suspect_urls),
        ):
            if values:
                add(f"{label:18}: {', '.join(values)}")
        if not any(
            [
                self.suspect_phone_numbers, self.suspect_upi_ids,
                self.suspect_bank_accounts, self.suspect_claimed_identity,
            ]
        ):
            add("  (none captured)")
        add("")

        add("-" * 72)
        add("3. EVIDENCE — RED FLAG EXCERPTS")
        add("-" * 72)
        if self.evidence:
            for i, e in enumerate(self.evidence, 1):
                stamp = f"[{e.timestamp}] " if e.timestamp else ""
                add(f"{i}. {stamp}{e.speaker}:")
                for line in _wrap(f'"{e.quote}"', 64):
                    add(f"     {line}")
                for line in _wrap(f"-> {e.significance}", 64):
                    add(f"     {line}")
                add("")
        else:
            add("  (none captured)")
            add("")

        if self.linked_cluster_id:
            add("-" * 72)
            add("4. LINKED FRAUD NETWORK")
            add("-" * 72)
            add(f"Cluster reference : {self.linked_cluster_id}")
            add(f"Linked sessions   : {self.linked_session_count}")
            if self.linked_sessions:
                add(f"Session refs      : {', '.join(self.linked_sessions)}")
            if self.network_note:
                add("")
                for line in _wrap(self.network_note, 68):
                    add(f"  {line}")
            add("")

        section = "5" if self.linked_cluster_id else "4"
        add("-" * 72)
        add(f"{section}. PROVISIONS POSSIBLY ENGAGED (illustrative)")
        add("-" * 72)
        for p in self.applicable_provisions or ["(not assessed)"]:
            add(f"  - {p}")
        add("")

        section = "6" if self.linked_cluster_id else "5"
        add("-" * 72)
        add(f"{section}. WHERE TO FILE")
        add("-" * 72)
        for c in self.recommended_channels:
            add(f"  - {c}")
        add("")
        add("=" * 72)
        for line in _wrap(self.disclaimer, 68):
            add(line)
        add("=" * 72)
        return "\n".join(lines)


def _wrap(text: str, width: int) -> list[str]:
    words = text.split()
    lines: list[str] = []
    current = ""
    for w in words:
        if len(current) + len(w) + 1 > width:
            if current:
                lines.append(current)
            current = w
        else:
            current = f"{current} {w}".strip()
    if current:
        lines.append(current)
    return lines or [""]
