"""Evidence & Reporting Agent.

Turns a confirmed-fraud session into a structured complaint draft.

The value here is narrow but real. A victim files a complaint hours later, from
memory, while distressed and often ashamed — and the details that actually let
police act (the exact UPI ID, the account number, the precise words used, the
timestamps) are exactly the details that evaporate under stress. We captured them
while the call was happening. This agent just assembles them.

The packet is **a draft**, not a filing. It is not submitted anywhere. It exists to
be reviewed by the person, then pasted into cybercrime.gov.in or handed to an
officer at a station.

Construction is deliberately mostly deterministic: identifiers, quotes, timestamps
and cluster references are assembled from data we already hold, not regenerated by
a model. The LLM writes only the prose summary. An invented account number in a
police complaint would be actively harmful, so the model is never given the chance
to produce one.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone

from app.config import get_settings, resolve_model_name
from app.models.advisory_schemas import ComplaintEvidence, ComplaintPacket
from app.models.graph_schemas import GraphMatch
from app.models.schemas import ClassifyResponse, RedFlagCategory, ScamType

logger = logging.getLogger(__name__)


COMPLAINT_DISCLAIMER = (
    "This is an AUTO-GENERATED DRAFT produced by AntiScam AI, a prototype system. "
    "It has NOT been filed with any authority and is NOT a legal document or legal "
    "advice. Statutory provisions listed are illustrative and may not be the ones "
    "actually applied. Review every detail for accuracy before submitting. To file "
    "for real, call 1930 or visit cybercrime.gov.in."
)

REPORTING_SYSTEM_PROMPT = """\
You are the Reporting Agent of AntiScam AI. You write the narrative summary of a \
cyber-fraud complaint that a victim will submit to Indian police.

Write for an investigating officer: factual, chronological, unemotional. This is a \
legal-adjacent document, not a story.

Rules:
- 3-6 sentences. Chronological: how contact was made, what was claimed, what \
pressure was applied, what was demanded.
- ONLY state facts present in the evidence given to you. Never invent an account \
number, phone number, name, amount, time, or case reference. If a detail is not \
provided, omit it — do not approximate it.
- Refer to the person as "the complainant" and the fraudster as "the caller".
- No adjectives of outrage. "The caller threatened arrest" — not "the caller \
cruelly terrorised the complainant".
- Do not assert legal conclusions ("this constitutes cheating under section X"). \
Describe conduct; let the officer classify it.

Respond with a single JSON object ONLY:
{"incident_summary": "<the narrative>"}
"""


# Statutory provisions by scam type. Illustrative — see knowledge_base.py.
_PROVISIONS_COMMON = [
    "IT Act, 2000 — Section 66D: Cheating by personation using a computer resource",
    "BNS, 2023 — Section 318: Cheating",
]

_PROVISIONS_BY_TYPE: dict[ScamType, list[str]] = {
    ScamType.DIGITAL_ARREST: [
        "BNS, 2023 — Section 319: Cheating by personation",
        "BNS, 2023 — Section 204: Personating a public servant",
        "BNS, 2023 — Section 308: Extortion",
        "IT Act, 2000 — Section 66C: Identity theft",
    ],
    ScamType.KYC_FRAUD: [
        "BNS, 2023 — Section 319: Cheating by personation",
        "IT Act, 2000 — Section 66C: Identity theft",
    ],
    ScamType.LOTTERY_PRIZE: ["BNS, 2023 — Section 319: Cheating by personation"],
    ScamType.LOAN_FRAUD: ["BNS, 2023 — Section 319: Cheating by personation"],
    ScamType.JOB_SCAM: ["BNS, 2023 — Section 319: Cheating by personation"],
    ScamType.INVESTMENT_FRAUD: ["BNS, 2023 — Section 319: Cheating by personation"],
    ScamType.TECH_SUPPORT: [
        "IT Act, 2000 — Section 66: Computer-related offences",
        "IT Act, 2000 — Section 66C: Identity theft",
    ],
}

_CHANNELS = [
    "National Cyber Crime Helpline: 1930 (call first — the 'golden hour' window "
    "can freeze funds still in the mule account)",
    "National Cyber Crime Reporting Portal: https://cybercrime.gov.in",
    "Your bank's fraud desk — ask them to raise a dispute and freeze the beneficiary",
    "Your nearest cyber crime police station, for a formal FIR",
]

_SIGNIFICANCE = {
    RedFlagCategory.AUTHORITY_IMPERSONATION: "Caller impersonated a public servant or institution.",
    RedFlagCategory.THREAT_OF_ARREST: "Threat of arrest used as coercion to obtain money.",
    RedFlagCategory.ISOLATION_TACTIC: "Complainant was instructed to remain on the call and not contact anyone.",
    RedFlagCategory.SECRECY_DEMAND: "Secrecy demanded under a fabricated legal pretext.",
    RedFlagCategory.FUND_TRANSFER_DEMAND: "Direct demand to transfer funds to a suspect account.",
    RedFlagCategory.CREDENTIAL_REQUEST: "Request for OTP/PIN/CVV — attempted unauthorised account access.",
    RedFlagCategory.FAKE_CASE_REFERENCE: "Fabricated case or FIR reference cited to establish false authority.",
    RedFlagCategory.VERIFICATION_PRETEXT: "False 'verification' pretext used to justify the demand.",
    RedFlagCategory.ADVANCE_FEE: "Advance fee demanded against a promised payout.",
    RedFlagCategory.UNREALISTIC_REWARD: "Non-existent reward used as inducement.",
    RedFlagCategory.REMOTE_ACCESS_REQUEST: "Attempt to obtain remote control of the complainant's device.",
    RedFlagCategory.URGENCY_PRESSURE: "Artificial time pressure applied to prevent verification.",
}


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _complaint_id(session_id: str) -> str:
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d")
    suffix = "".join(c for c in session_id if c.isalnum())[-6:].upper() or "000000"
    return f"ASAI-{stamp}-{suffix}"


def _fallback_summary(detection: ClassifyResponse, match: GraphMatch | None) -> str:
    flags = ", ".join(
        f.category.value.replace("_", " ") for f in detection.red_flags[:5]
    )
    parts = [
        f"The complainant received a communication assessed by AntiScam AI as "
        f"{detection.scam_type.value.replace('_', ' ')} with a risk score of "
        f"{detection.scam_probability}/100."
    ]
    if flags:
        parts.append(f"The following coercion patterns were identified: {flags}.")
    if detection.extracted_entities.claimed_departments:
        parts.append(
            "The caller claimed to represent: "
            f"{', '.join(detection.extracted_entities.claimed_departments)}."
        )
    if match and match.is_repeat_scammer:
        parts.append(
            f"Identifiers in this incident match {match.total_victims_in_cluster} "
            f"previously recorded session(s) (cluster {match.cluster_id})."
        )
    return " ".join(parts)


def _generate_summary(
    detection: ClassifyResponse, match: GraphMatch | None
) -> tuple[str, bool]:
    """Returns (summary, degraded)."""
    settings = get_settings()
    if not settings.groq_configured:
        return _fallback_summary(detection, match), True

    evidence_block = "\n".join(
        f'- [{f.timestamp or "no timestamp"}] {f.category.value}: "{f.quote}"'
        for f in detection.red_flags[:10]
    )
    e = detection.extracted_entities
    identifiers = "\n".join(
        f"- {label}: {', '.join(vals)}"
        for label, vals in (
            ("Phone numbers", e.phone_numbers),
            ("UPI IDs", e.upi_ids),
            ("Bank accounts", e.bank_accounts),
            ("Claimed identity", e.claimed_names),
            ("Claimed agency", e.claimed_departments),
            ("Case references cited", e.case_numbers),
            ("Amounts mentioned", e.amounts_mentioned),
        )
        if vals
    )
    network = ""
    if match and match.is_repeat_scammer:
        network = (
            f"\n\nFRAUD NETWORK: identifiers match {match.total_victims_in_cluster} "
            f"prior session(s), cluster {match.cluster_id}."
        )

    prompt = f"""Write the incident summary for this complaint.

ASSESSMENT: {detection.scam_type.value}, risk {detection.scam_probability}/100
ANALYSIS: {detection.reasoning}

QUOTED EVIDENCE:
{evidence_block or "(none)"}

IDENTIFIERS CAPTURED:
{identifiers or "(none)"}{network}

Return JSON with the incident_summary."""

    try:
        from groq import Groq

        client = Groq(
            api_key=settings.groq_api_key,
            timeout=settings.request_timeout,
            max_retries=0,
        )
        completion = client.chat.completions.create(
            model=resolve_model_name(),
            messages=[
                {"role": "system", "content": REPORTING_SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ],
            temperature=0.2,
            max_completion_tokens=700,
            response_format={"type": "json_object"},
            seed=13,
        )
        payload = json.loads(completion.choices[0].message.content or "")
        summary = str(payload.get("incident_summary", "")).strip()
        if not summary:
            raise ValueError("empty incident_summary")
        return summary, False
    except Exception as exc:
        logger.warning(
            "Reporting summary generation failed (%s); using deterministic fallback.",
            type(exc).__name__,
        )
        return _fallback_summary(detection, match), True


def build_complaint(
    session_id: str,
    detection: ClassifyResponse,
    match: GraphMatch | None = None,
) -> ComplaintPacket:
    """Assemble an NCRB-style complaint draft from a confirmed-fraud session."""
    summary, degraded = _generate_summary(detection, match)

    evidence = [
        ComplaintEvidence(
            timestamp=f.timestamp,
            turn_index=f.turn_index,
            speaker="caller",
            quote=f.quote,
            significance=_SIGNIFICANCE.get(
                f.category, f.category.value.replace("_", " ").capitalize()
            ),
        )
        for f in detection.red_flags
    ]

    provisions = _PROVISIONS_BY_TYPE.get(detection.scam_type, []) + _PROVISIONS_COMMON
    # Preserve order while removing duplicates.
    provisions = list(dict.fromkeys(provisions))

    e = detection.extracted_entities
    network_note = None
    if match and match.is_repeat_scammer:
        network_note = (
            f"{match.summary} This indicates an organised operation rather than an "
            f"isolated incident, and the linked sessions may support a consolidated "
            f"investigation."
        )

    return ComplaintPacket(
        complaint_id=_complaint_id(session_id),
        generated_at=_now(),
        session_id=session_id,
        incident_type=detection.scam_type.value.replace("_", " ").title(),
        incident_summary=summary,
        scam_probability=detection.scam_probability,
        estimated_loss=e.amounts_mentioned[0] if e.amounts_mentioned else None,
        suspect_phone_numbers=e.phone_numbers,
        suspect_upi_ids=e.upi_ids,
        suspect_bank_accounts=e.bank_accounts,
        suspect_claimed_identity=e.claimed_names,
        suspect_claimed_agency=e.claimed_departments,
        fake_case_references=e.case_numbers,
        suspect_urls=e.urls,
        evidence=evidence,
        linked_cluster_id=match.cluster_id if match and match.is_repeat_scammer else None,
        linked_session_count=match.total_victims_in_cluster if match and match.is_repeat_scammer else 0,
        linked_sessions=[s.session_id for s in match.linked_sessions] if match else [],
        network_note=network_note,
        applicable_provisions=provisions,
        recommended_channels=list(_CHANNELS),
        disclaimer=COMPLAINT_DISCLAIMER,
        degraded=degraded,
    )
